export const SERVICES_PUBSUB = 'SERVICES_PUBSUB';
export const SERVICES_KV_STORAGE = 'SERVICES_KV_STORAGE';
export const SERVICES_KS_STORAGE = 'SERVICES_KS_STORAGE';
export const INJECT_PROP_MODULE_MAP = '__INJECT_PROP_MODULE_MAP';
